### ISSUE TITLE
power1_solar is not a valid option

### ISSUE THREAD

**Issue by andrewagner86** [EldarKarahasanovic/myPVHomeAssistant#1]
I'm using an AC-ELWA E
power1_solar is preselected and cannot be deselected

![image](https://github.com/user-attachments/assets/9770e0cc-7ba2-4a25-ae2a-aca0559813b0)

**Comment by melik787** [comment]
Fixed this issue by removing power1_solar from the DEFAULT_MONITORED_CONDITIONS list
