### ISSUE TITLE
Does'nt work with ELWA-E

### ISSUE THREAD

**Issue by LC44fun** [EldarKarahasanovic/myPVHomeAssistant#6]
![image](https://github.com/user-attachments/assets/7329f0e3-4b71-41f7-a2cd-0b4bbae13b29)

ELWA-E does'nt have a display. It is not possible to unselect the screen_mode_flag.

**Comment by B0bby31** [comment]
+1 this. I was just looking into your new and improved extension and it would be greatly appreciated if you fix this.

zaubererty/homeassistant-mypv#3 contains the data available from the ac elwa e

**Comment by d0h0** [comment]
Hey guys! Thanks for your input, I will test and give feedback tomorrow.

**Comment by d0h0** [comment]
@LC44fun can you confirm it works with 1.2 release?

Thank you.

**Comment by LC44fun** [comment]
I used meanwhile the fork of B0bby31, and changed now back to this release. After new download and restart the Home assistant-instance it seems to work well. So I did'nt remove everything, before switching to the main version.
Currently it seems to work. I will give a confirmation after some days of testing.
Thanks for your support.
